-- SANDU MATEI, GRUPA 1059 - RETEAUA DE CAMINE ASE

-- first step: cleaning

drop table plati_salarii cascade constraints;
drop table angajat_sporuri cascade constraints;
drop table tipuri_sporuri cascade constraints;
drop table personal_camin cascade constraints;
drop table staff cascade constraints;
drop table facturi_cazare cascade constraints;
drop table cazari cascade constraints;
drop table studenti cascade constraints;
drop table lista_preturi_camin cascade constraints;
drop table camere cascade constraints;
drop table camine cascade constraints;
drop sequence seq_facturi;
drop view v_lista_publica_studenti;
drop synonym tarife;


--2nd step: defining structure

create table camine (
    id_camin number generated by default as identity, -- auto-increment
    cod_camin varchar2(20) not null,
    nume_camin varchar2(100),
    adresa varchar2(200),
    if_mixt number(1) default 0, 
    constraint pk_camine primary key (id_camin),
    constraint uq_cod_camin unique (cod_camin),
    constraint ck_mixt check (if_mixt in (0, 1))
);

create table lista_preturi_camin (
    id_pret number generated by default as identity,
    id_camin number not null,
    an_universitar varchar2(9) not null, 
    pret_buget number(10, 2) not null,
    pret_taxa number(10, 2) not null,
    constraint pk_lista_preturi primary key (id_pret),
    constraint fk_pret_camin foreign key (id_camin) references camine(id_camin),
    constraint uq_pret_an_camin unique (id_camin, an_universitar)
);

create table camere (
    id_camera number generated by default as identity,
    id_camin number not null,
    nr_camera varchar2(10) not null, 
    etaj number(2),
    capacitate number(2) not null,
    constraint pk_camere primary key (id_camera),
    constraint fk_camere_camin foreign key (id_camin) references camine(id_camin),
    constraint uq_camera_in_camin unique (id_camin, nr_camera),
    constraint ck_capacitate_pozitiva check (capacitate > 0)
);

create table studenti (
    id_student number generated by default as identity,
    nr_matricol varchar2(20) not null,
    nume varchar2(50) not null,
    prenume varchar2(50) not null,
    cnp varchar2(13) not null,
    sex varchar2(1), 
    facultate varchar2(100),
    specializare varchar2(100), 
    an_curent varchar2(2),        
    an_inceput_studii number(4), 
    forma_finantare varchar2(20) not null,
    status_student varchar2(20) default 'activ',
    email varchar2(100),
    constraint pk_studenti primary key (id_student),
    constraint uq_matricol unique (nr_matricol),
    constraint uq_cnp unique (cnp),
    constraint ck_finantare check (forma_finantare in ('buget', 'taxa', 'social')),
    constraint ck_sex check (sex in ('m', 'f')),
    constraint ck_an_curent check (an_curent in ('1', '2', '3', 'M1', 'M2')) 
);

create table cazari (
    id_cazare number generated by default as identity,
    id_student number not null,
    id_camera number not null,
    an_universitar varchar2(9) not null, 
    data_start date default sysdate,
    data_final date,
    status_cazare varchar2(20) default 'activ',
    constraint pk_cazari primary key (id_cazare),
    constraint fk_cazari_student foreign key (id_student) references studenti(id_student),
    constraint fk_cazari_camera foreign key (id_camera) references camere(id_camera),
    constraint ck_date_valide check (data_final >= data_start)
);

create table facturi_cazare (
    id_factura number,
    id_cazare number not null,
    luna number(2) not null,
    anul number(4) not null,
    suma_plata number(10, 2) not null,
    data_emitere date,
    status_factura varchar2(20) default 'neplatit', 
    constraint pk_facturi primary key (id_factura),
    constraint fk_facturi_cazare foreign key (id_cazare) references cazari(id_cazare),
    constraint ck_luna check (luna between 1 and 12),
    constraint ck_suma_pozitiva check (suma_plata > 0)
);

create table staff (
    id_staff number generated by default as identity,
    nume varchar2(50) not null,
    prenume varchar2(50) not null,
    cnp varchar2(13) not null,
    functie_baza varchar2(50), 
    salariu_baza number(10, 2), 
    email_institutional varchar2(100),
    constraint pk_staff primary key (id_staff),
    constraint uq_cnp_staff unique (cnp)
);

create table tipuri_sporuri (
    id_spor number generated by default as identity,
    nume_spor varchar2(50) not null, 
    procent number(5, 2) not null, 
    constraint pk_sporuri primary key (id_spor)
);

create table angajat_sporuri (
    id_asoc number generated by default as identity,
    id_staff number not null,
    id_spor number not null,
    constraint pk_angajat_spor primary key (id_asoc),
    constraint fk_asoc_staff foreign key (id_staff) references staff(id_staff),
    constraint fk_asoc_spor foreign key (id_spor) references tipuri_sporuri(id_spor)
);

create table plati_salarii (
    id_plata number generated by default as identity,
    id_staff number not null,
    luna number(2) not null,
    anul number(4) not null,
    data_platii date,
    salariu_baza_istoric number(10, 2),
    total_sporuri_lei number(10, 2),
    salariu_final_net number(10, 2),
    constraint pk_plati primary key (id_plata),
    constraint fk_plati_staff foreign key (id_staff) references staff(id_staff)
);

create table personal_camin (
    id_contract number generated by default as identity,
    id_staff number not null,
    id_camin number not null,
    data_start_contract date default sysdate,
    constraint pk_personal_camin primary key (id_contract),
    constraint fk_pers_staff foreign key (id_staff) references staff(id_staff),
    constraint fk_pers_camin foreign key (id_camin) references camine(id_camin)
);

--3rd step: modyfying structure
alter table studenti add telefon varchar2(15);
alter table staff add constraint ck_salariu_minim check (salariu_baza >= 2500);
alter table studenti modify email varchar2(150);


--4th step: insert data
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('moxa', 'Complex Moxa D', 'Mihail Moxa 11', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a6', 'Belvedere Nou A6', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a7', 'Belvedere Nou A7', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a8', 'Belvedere Nou A8', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('tei', 'Complex Tei C1', 'Lacul Tei 116', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a1', 'Belvedere Vechi A1', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a2', 'Belvedere Vechi A2', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a3', 'Belvedere Vechi A3', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a4', 'Belvedere Vechi A4', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('agro-c1', 'Agronomie C1', 'Marasti 59', 0);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('agro-c2', 'Agronomie C2', 'Marasti 59', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('occid', 'Occidentului', 'Occidentului 7', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('vitan', 'Vitan Center', 'Energeticienilor 9', 1);
--query check
select * from camine;


insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 200, 400 
from camine 
where lower(nume_camin) like '%moxa%' or lower(nume_camin) like '%belvedere nou%' or lower(nume_camin) like '%tei%';

insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 150, 290 
from camine 
where lower(nume_camin) like '%belvedere vechi%' or lower(nume_camin) like '%agronomie%' or lower(nume_camin) like '%vitan%';

insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 650, 800 
from camine 
where lower(nume_camin) like '%occidentului%';
--query check
select c.nume_camin, l.pret_buget, l.pret_taxa 
from lista_preturi_camin l 
join camine c on l.id_camin = c.id_camin
order by l.pret_buget desc;


insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 4
from camine c
cross join (select level as etaj from dual connect by level <= 6) 
cross join (select level as cam from dual connect by level <= 8)  
where lower(c.nume_camin) like '%moxa%' or lower(c.nume_camin) like '%belvedere nou%'; -- moxa/belv nou

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 4
from camine c
cross join (select level + 3 as etaj from dual connect by level <= 2) 
cross join (select level as cam from dual connect by level <= 20)
where lower(c.nume_camin) like '%tei%'; -- tei

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, case when lower(c.nume_camin) like '%agronomie%' then 3 else 2 end
from camine c
cross join (select level as etaj from dual connect by level <= 2) 
cross join (select level as cam from dual connect by level <= 15)
where lower(c.nume_camin) like '%belvedere vechi%' or lower(c.nume_camin) like '%agronomie%'; --agro/belv vechi

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 2
from camine c
cross join (select level as etaj from dual connect by level <= 6)
cross join (select level as cam from dual connect by level <= 5)
where lower(c.nume_camin) like '%occidentului%'; -- occidentului

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 2
from camine c
cross join (select level as etaj from dual connect by level <= 4)
cross join (select level as cam from dual connect by level <= 10)
where lower(c.nume_camin) like '%vitan%'; --vitan
--query check for camere
select c.nume_camin, count(*) as numar_camere, sum(cam.capacitate) as total_locuri
from camere cam
join camine c on cam.id_camin = c.id_camin
group by c.nume_camin
order by c.nume_camin;

insert into studenti (nr_matricol, nume, prenume, cnp, sex, facultate, specializare, an_curent, an_inceput_studii, forma_finantare, email)
select 
    lower(substr(fac_code, 1, 3)) || '_' || to_char(rownum + 100),
    initcap(nume_real),
    initcap(prenume_real),
    (case sex_real when 'm' then 5 else 6 end) || substr(to_char(an_start - 19), 3, 2) || '0000' || to_char(rownum + 1000),
    sex_real,
    nume_facultate,
    nume_specializare,
    case when (2025 - an_start + 1) = 1 then '1' when (2025 - an_start + 1) = 2 then '2' when (2025 - an_start + 1) = 3 then '3' when (2025 - an_start + 1) = 4 then 'M1' else 'M2' end,
    an_start,
    'buget',
    email_real
from (
    select nume_real, prenume_real, sex_real, an_start, email_real,
        case mod(rownum, 26) when 0 then 'FABIZ' when 1 then 'FABIZ' when 2 then 'FABIZ' when 3 then 'AMP' when 4 then 'AMP' when 5 then 'BT' when 6 then 'BT' when 7 then 'CSIE' when 8 then 'CSIE' when 9 then 'CSIE' when 10 then 'CIG' when 11 then 'CIG' when 12 then 'DREPT' when 13 then 'ECA' when 14 then 'ECA' when 15 then 'EAM' when 16 then 'EAM' when 17 then 'FABBV' when 18 then 'FABBV' when 19 then 'MAN' when 20 then 'MAN' when 21 then 'MK' when 22 then 'MK' when 23 then 'REI' when 24 then 'REI' else 'BBS' end as fac_code,
        case mod(rownum, 26) when 0 then 'Administrarea Afacerilor (FABIZ)' when 1 then 'Administrarea Afacerilor (FABIZ)' when 2 then 'Administrarea Afacerilor (FABIZ)' when 3 then 'Administratie si Management Public' when 4 then 'Administratie si Management Public' when 5 then 'Business si Turism' when 6 then 'Business si Turism' when 7 then 'Cibernetica, Statistica si Informatica' when 8 then 'Cibernetica, Statistica si Informatica' when 9 then 'Cibernetica, Statistica si Informatica' when 10 then 'Contabilitate si Informatica de Gestiune' when 11 then 'Contabilitate si Informatica de Gestiune' when 12 then 'Drept' when 13 then 'Economie si Comunicare in Afaceri' when 14 then 'Economie si Comunicare in Afaceri' when 15 then 'Economie Agroalimentara si a Mediului' when 16 then 'Economie Agroalimentara si a Mediului' when 17 then 'Finante, Asigurari, Banci si Burse' when 18 then 'Finante, Asigurari, Banci si Burse' when 19 then 'Management' when 20 then 'Management' when 21 then 'Marketing' when 22 then 'Marketing' when 23 then 'Relatii Economice Internationale' when 24 then 'Relatii Economice Internationale' else 'Bucharest Business School' end as nume_facultate,
        case mod(rownum, 26) when 0 then 'Administrarea Afacerilor (Engleza)' when 1 then 'Administrarea Afacerilor (Germana)' when 2 then 'Administrarea Afacerilor (Franceza)' when 3 then 'Administratie Publica' when 4 then 'Resurse Umane' when 5 then 'Business si Turism' when 6 then 'Merceologie si Management' when 7 then 'Informatica Economica' when 8 then 'Cibernetica Economica' when 9 then 'Statistica si Previziune' when 10 then 'Contabilitate si Info de Gestiune' when 11 then 'Contabilitate si Audit' when 12 then 'Drept' when 13 then 'Comunicare in Afaceri' when 14 then 'Economie Generala' when 15 then 'Economie Agroalimentara' when 16 then 'Ecologie si Protectia Mediului' when 17 then 'Finante si Banci' when 18 then 'Finante si Banci (Engleza)' when 19 then 'Management' when 20 then 'Management (Engleza)' when 21 then 'Marketing' when 22 then 'Marketing (Engleza)' when 23 then 'Economie si Afaceri Int.' when 24 then 'Limbi Moderne Aplicate' else 'MBA Romano-Canadian' end as nume_specializare
    from (
        select 'popescu' nume_real, 'andrei' prenume_real, 'm' sex_real, 2025 an_start, 'popescuandrei25@stud.ase.ro' email_real from dual union all
        select 'ionescu', 'maria', 'f', 2021, 'ionescumaria21@stud.ase.ro' from dual union all
        select 'radu', 'vlad', 'm', 2024, 'raduvlad24@stud.ase.ro' from dual union all
        select 'dumitru', 'elena', 'f', 2023, 'dumitruelena23@stud.ase.ro' from dual union all
        select 'stoica', 'george', 'm', 2022, 'stoicageorge22@stud.ase.ro' from dual union all
        select 'stan', 'ioana', 'f', 2025, 'stanioana25@stud.ase.ro' from dual union all
        select 'gheorghe', 'david', 'm', 2021, 'gheorghedavid21@stud.ase.ro' from dual union all
        select 'mihai', 'alexandru', 'm', 2024, 'mihaialexandru24@stud.ase.ro' from dual union all
        select 'constantin', 'ana', 'f', 2023, 'constantinana23@stud.ase.ro' from dual union all
        select 'enache', 'ionut', 'm', 2022, 'enacheionut22@stud.ase.ro' from dual union all
        select 'vasilescu', 'mihai', 'm', 2025, 'vasilescumihai25@stud.ase.ro' from dual union all
        select 'marin', 'andreea', 'f', 2024, 'marinandreea24@stud.ase.ro' from dual union all
        select 'dinu', 'stefan', 'm', 2021, 'dinustefan21@stud.ase.ro' from dual union all
        select 'tudor', 'gabriel', 'm', 2022, 'tudorgabriel22@stud.ase.ro' from dual union all
        select 'nistor', 'cristina', 'f', 2023, 'nistorcristina23@stud.ase.ro' from dual union all
        select 'florea', 'robert', 'm', 2025, 'florearobert25@stud.ase.ro' from dual union all
        select 'mocanu', 'diana', 'f', 2024, 'mocanudiana24@stud.ase.ro' from dual union all
        select 'oprea', 'daniel', 'm', 2021, 'opreadaniel21@stud.ase.ro' from dual union all
        select 'barbu', 'alexia', 'f', 2022, 'barbualexia22@stud.ase.ro' from dual union all
        select 'neagu', 'cosmin', 'm', 2023, 'neagucosmin23@stud.ase.ro' from dual union all
        select 'popa', 'stefan', 'm', 2025, 'popastefan25@stud.ase.ro' from dual union all
        select 'rusu', 'denisa', 'f', 2024, 'rusudenisa24@stud.ase.ro' from dual union all
        select 'munteanu', 'razvan', 'm', 2021, 'munteanurazvan21@stud.ase.ro' from dual union all
        select 'matei', 'catalina', 'f', 2022, 'mateicatalina22@stud.ase.ro' from dual union all
        select 'serban', 'eduard', 'm', 2023, 'serbaneduard23@stud.ase.ro' from dual union all
        select 'lazar', 'bianca', 'f', 2025, 'lazarbianca25@stud.ase.ro' from dual union all
        select 'moldovan', 'florin', 'm', 2024, 'moldovanflorin24@stud.ase.ro' from dual union all
        select 'vasile', 'teodora', 'f', 2021, 'vasileteodora21@stud.ase.ro' from dual union all
        select 'dragan', 'alexandra', 'f', 2022, 'draganalexandra22@stud.ase.ro' from dual union all
        select 'sandu', 'cristian', 'm', 2023, 'sanducristian23@stud.ase.ro' from dual union all
        select 'voinea', 'laura', 'f', 2025, 'voinealaura25@stud.ase.ro' from dual union all
        select 'albu', 'adrian', 'm', 2024, 'albuadrian24@stud.ase.ro' from dual union all
        select 'diaconu', 'georgiana', 'f', 2021, 'diaconugeorgiana21@stud.ase.ro' from dual union all
        select 'petrescu', 'victor', 'm', 2022, 'petrescuvictor22@stud.ase.ro' from dual union all
        select 'ciobanu', 'alina', 'f', 2023, 'ciobanualina23@stud.ase.ro' from dual union all
        select 'toma', 'marius', 'm', 2025, 'tomamarius25@stud.ase.ro' from dual union all
        select 'pavel', 'andrada', 'f', 2024, 'pavelandrada24@stud.ase.ro' from dual union all
        select 'cristea', 'rares', 'm', 2021, 'cristearares21@stud.ase.ro' from dual union all
        select 'florescu', 'monica', 'f', 2022, 'florescumonica22@stud.ase.ro' from dual union all
        select 'dobre', 'silviu', 'm', 2023, 'dobresilviu23@stud.ase.ro' from dual union all
        select 'ungureanu', 'camelia', 'f', 2025, 'ungureanucamelia25@stud.ase.ro' from dual union all
        select 'ionescu', 'dan', 'm', 2024, 'ionescudan24@stud.ase.ro' from dual union all
        select 'dumitrache', 'ioana', 'f', 2021, 'dumitracheioana21@stud.ase.ro' from dual union all
        select 'avram', 'bogdan', 'm', 2022, 'avrambogdan22@stud.ase.ro' from dual union all
        select 'nedelea', 'valentina', 'f', 2023, 'nedeleavalentina23@stud.ase.ro' from dual union all
        select 'stanciu', 'mihai', 'm', 2025, 'stanciumihai25@stud.ase.ro' from dual union all
        select 'coman', 'larisa', 'f', 2024, 'comanlarisa24@stud.ase.ro' from dual union all
        select 'apostol', 'paul', 'm', 2021, 'apostolpaul21@stud.ase.ro' from dual union all
        select 'manole', 'eliza', 'f', 2022, 'manoleeliza22@stud.ase.ro' from dual union all
        select 'negru', 'sebastian', 'm', 2023, 'negrusebastian23@stud.ase.ro' from dual union all
        select 'preda', 'antonia', 'f', 2025, 'predaantonia25@stud.ase.ro' from dual union all
        select 'voicu', 'sergiu', 'm', 2024, 'voicusergiu24@stud.ase.ro' from dual union all
        select 'cojocaru', 'madalina', 'f', 2021, 'cojocarumadalina21@stud.ase.ro' from dual union all
        select 'badea', 'lucian', 'm', 2022, 'badealuciau22@stud.ase.ro' from dual union all
        select 'ionita', 'marian', 'm', 2023, 'ionitamarian23@stud.ase.ro' from dual union all
        select 'olaru', 'rebeca', 'f', 2025, 'olarurebeca25@stud.ase.ro' from dual union all
        select 'tanase', 'costin', 'm', 2024, 'tanasecostin24@stud.ase.ro' from dual union all
        select 'danila', 'marilena', 'f', 2021, 'danilamarilena21@stud.ase.ro' from dual union all
        select 'filip', 'alex', 'm', 2022, 'filipalex22@stud.ase.ro' from dual union all
        select 'simion', 'robert', 'm', 2023, 'simionrobert23@stud.ase.ro' from dual union all
        select 'grosu', 'daria', 'f', 2025, 'grosudaria25@stud.ase.ro' from dual union all
        select 'lazarescu', 'matei', 'm', 2024, 'lazarescumatei24@stud.ase.ro' from dual union all
        select 'marcu', 'adriana', 'f', 2021, 'marcuadriana21@stud.ase.ro' from dual union all
        select 'parvu', 'gabriel', 'm', 2022, 'parvugabriel22@stud.ase.ro' from dual union all
        select 'rotaru', 'cosmina', 'f', 2023, 'rotarucosmina23@stud.ase.ro' from dual union all
        select 'teodorescu', 'dorin', 'm', 2025, 'teodorescudorin25@stud.ase.ro' from dual union all
        select 'maria', 'nicoleta', 'f', 2024, 'marianicoleta24@stud.ase.ro' from dual union all
        select 'ifrim', 'sorin', 'm', 2021, 'ifrimsorin21@stud.ase.ro' from dual union all
        select 'alex', 'elena', 'f', 2022, 'alexelena22@stud.ase.ro' from dual union all
        select 'balan', 'petru', 'm', 2023, 'balanpetru23@stud.ase.ro' from dual union all
        select 'zamfir', 'raluca', 'f', 2025, 'zamfirraluca25@stud.ase.ro' from dual union all
        select 'niculae', 'cristi', 'm', 2024, 'niculaecristi24@stud.ase.ro' from dual union all
        select 'calin', 'beatrice', 'f', 2021, 'calinbeatrice21@stud.ase.ro' from dual union all
        select 'tamas', 'vladimir', 'm', 2022, 'tamasvladimir22@stud.ase.ro' from dual union all
        select 'david', 'sonia', 'f', 2023, 'davidsonia23@stud.ase.ro' from dual union all
        select 'ghenghea', 'ovidiu', 'm', 2025, 'ghengheaovidiu25@stud.ase.ro' from dual union all
        select 'iancu', 'emilia', 'f', 2024, 'iancuemilia24@stud.ase.ro' from dual union all
        select 'moculescu', 'horia', 'm', 2021, 'moculescuhoria21@stud.ase.ro' from dual union all
        select 'trandafir', 'sofia', 'f', 2022, 'trandafirsofia22@stud.ase.ro' from dual union all
        select 'costea', 'claudiu', 'm', 2023, 'costeaclaudiu23@stud.ase.ro' from dual union all
        select 'lungu', 'tiberiu', 'm', 2025, 'lungutiberiu25@stud.ase.ro' from dual union all
        select 'burlacu', 'iulia', 'f', 2024, 'burlacuiulia24@stud.ase.ro' from dual union all
        select 'cretu', 'vasile', 'm', 2021, 'cretuvasile21@stud.ase.ro' from dual union all
        select 'arsene', 'octavian', 'm', 2022, 'arseneoctavian22@stud.ase.ro' from dual union all
        select 'ignat', 'patricia', 'f', 2023, 'ignatpatricia23@stud.ase.ro' from dual union all
        select 'savu', 'mircea', 'm', 2025, 'savumircea25@stud.ase.ro' from dual union all
        select 'milea', 'florina', 'f', 2024, 'mileaflorina24@stud.ase.ro' from dual union all
        select 'luca', 'andrei', 'm', 2021, 'lucaandrei21@stud.ase.ro' from dual union all
        select 'olteanu', 'carmen', 'f', 2022, 'olteanucarmen22@stud.ase.ro' from dual union all
        select 'miron', 'liviu', 'm', 2023, 'mironliviu23@stud.ase.ro' from dual union all
        select 'suciu', 'stephanie', 'f', 2025, 'suciustephanie25@stud.ase.ro' from dual union all
        select 'pascu', 'dorin', 'm', 2024, 'pascudorin24@stud.ase.ro' from dual union all
        select 'vintila', 'anca', 'f', 2021, 'vintilaanca21@stud.ase.ro' from dual union all
        select 'roman', 'felix', 'm', 2022, 'romanfelix22@stud.ase.ro' from dual union all
        select 'zaharia', 'emanuel', 'm', 2023, 'zahariaemanuel23@stud.ase.ro' from dual union all
        select 'anton', 'irina', 'f', 2025, 'antonirina25@stud.ase.ro' from dual union all
        select 'bordea', 'albert', 'm', 2024, 'bordeaalbert24@stud.ase.ro' from dual union all
        select 'stroe', 'ilinca', 'f', 2021, 'stroeilinca21@stud.ase.ro' from dual union all
        select 'codreanu', 'filip', 'm', 2022, 'codreanufilip22@stud.ase.ro' from dual
    )
);

--query check for studenti, simple count check
select specializare, count(*) from studenti group by specializare order by 1;


insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Andrei', 'Lenuta', '2800101123456', 'Administrator', 4500, 'andrei.lenuta@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Bardac', 'Geta', '2810202123456', 'Administrator', 4500, 'bardac.geta@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Iosif', 'Alexandru', '1790303123456', 'Administrator', 4200, 'iosif.alexandru@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Padure', 'Andrei', '1850404123456', 'Administrator', 4000, 'padure.andrei@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Ghiur', 'Silvia', '2750505123456', 'Administrator', 4100, 'ghiur.silvia@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Popescu', 'Constantin', '1600606123456', 'Administrator', 5000, 'popescu.constantin@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Vargatiuc', 'Mihaela', '2820707123456', 'Administrator', 4300, 'mihaela.vargatiuc@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza) values ('Ionescu', 'Vasile', '1700101999999', 'Instalator', 3500);
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza) values ('Popa', 'Maria', '2700101888888', 'Femeie de Serviciu', 2800);

insert into tipuri_sporuri (nume_spor, procent) values ('Spor Vechime', 0.15);
insert into tipuri_sporuri (nume_spor, procent) values ('Spor Conducere', 0.25);
insert into tipuri_sporuri (nume_spor, procent) values ('Spor Toxicitate', 0.10);

insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where s.functie_baza = 'Administrator' and t.nume_spor = 'Spor Conducere';
insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where t.nume_spor = 'Spor Vechime';
insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where s.functie_baza = 'Instalator' and t.nume_spor = 'Spor Toxicitate';

insert into personal_camin (id_staff, id_camin, data_start_contract)
select s.id_staff, c.id_camin, add_months(sysdate, -round(dbms_random.value(1, 60)))
from staff s
join camine c on (s.nume = 'Andrei' and c.cod_camin = 'moxa') or (s.nume = 'Bardac' and c.cod_camin = 'belv-a6') or (s.nume = 'Iosif' and c.cod_camin = 'tei') or (s.nume = 'Padure' and c.cod_camin = 'belv-a1') or (s.nume = 'Ghiur' and c.cod_camin = 'agro-c1') or (s.nume = 'Popescu' and c.cod_camin = 'occid') or (s.nume = 'Vargatiuc' and c.cod_camin = 'vitan');


insert into cazari (id_student, id_camera, an_universitar, status_cazare)
select s.id_student, match.id_camera, '2024-2025', 'activ'
from studenti s
join (
    select st.id_student, cm.id_camera, row_number() over (partition by st.id_student order by dbms_random.value) as rn
    from studenti st
    join camine k on 1=1 join camere cm on k.id_camin = cm.id_camin
    where st.sex = 'f' and (k.if_mixt = 1 or k.nume_camin like '%Fete%' or k.cod_camin in ('belv-a1', 'belv-a2', 'belv-a3', 'agro-c1'))
) match on s.id_student = match.id_student
where match.rn = 1;

insert into cazari (id_student, id_camera, an_universitar, status_cazare)
select s.id_student, match.id_camera, '2024-2025', 'activ'
from studenti s
join (
    select st.id_student, cm.id_camera, row_number() over (partition by st.id_student order by dbms_random.value) as rn
    from studenti st
    join camine k on 1=1 join camere cm on k.id_camin = cm.id_camin
    where st.sex = 'm' and (k.if_mixt = 1 or k.nume_camin like '%Baieti%' or k.cod_camin in ('belv-a4', 'agro-c2')) and cm.id_camera not in (select id_camera from cazari)
) match on s.id_student = match.id_student
where match.rn = 1;

--query check if a room has students of different sexes, should return 0 rows
select c.id_camera, count(distinct s.sex) as mix_sex
from cazari c
join studenti s on c.id_student = s.id_student
group by c.id_camera
having count(distinct s.sex) > 1;

-- list of students with their accommodation details
select initcap(s.nume) || ' ' || initcap(s.prenume) as student, s.sex, k.nume_camin, cm.nr_camera
from cazari z
join studenti s on z.id_student = s.id_student
join camere cm on z.id_camera = cm.id_camera
join camine k on cm.id_camin = k.id_camin
order by k.nume_camin, cm.nr_camera;


create sequence seq_facturi start with 1000 increment by 1; -- sequence for invoice IDs

insert into facturi_cazare (id_factura, id_cazare, luna, anul, suma_plata, data_emitere, status_factura)
select seq_facturi.nextval, z.id_cazare, extract(month from calendar.data_luna), extract(year from calendar.data_luna), case when s.forma_finantare = 'buget' then p.pret_buget else p.pret_taxa end, calendar.data_luna, 'neplatit'
from cazari z
join studenti s on z.id_student = s.id_student
join camere cm on z.id_camera = cm.id_camera
join lista_preturi_camin p on cm.id_camin = p.id_camin
cross join (select add_months(to_date('01-09-2025', 'dd-mm-yyyy'), level - 1) as data_luna from dual connect by level <= 10) calendar;

insert into plati_salarii (id_staff, luna, anul, data_platii, salariu_baza_istoric, total_sporuri_lei, salariu_final_net)
select s.id_staff, cal.luna, 2025, to_date('25-' || lpad(cal.luna, 2, '0') || '-2025', 'dd-mm-yyyy'), s.salariu_baza, round(s.salariu_baza * (select nvl(sum(ts.procent), 0) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff), 2), round(s.salariu_baza + (s.salariu_baza * (select nvl(sum(ts.procent), 0) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff)), 2)
from staff s
cross join (select level as luna from dual connect by level <= 12) cal;

commit;

--query check for plati_salarii
select initcap(s.nume) || ' ' || initcap(s.prenume) as angajat, s.functie_baza, p.luna, p.salariu_baza_istoric as baza,
    (select listagg(ts.nume_spor || ' (' || (ts.procent*100) || '%)', ', ') within group (order by ts.nume_spor) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff) as lista_sporuri,
    p.total_sporuri_lei as valoare_spor, p.salariu_final_net as total_incasat
from plati_salarii p
join staff s on p.id_staff = s.id_staff
where p.luna = 10 
order by p.salariu_final_net desc;


--using update functions
update staff set salariu_baza = salariu_baza * 1.1 where functie_baza = 'Administrator';
update studenti set telefon = '0722123456' where nume = 'Popescu' and prenume = 'Andrei';
commit;


--drop and rollback example
create table avizier (id_anunt number, mesaj varchar2(100));
insert into avizier values (1, 'Curatenie generala Marti');
commit;
delete from avizier; -- stergem datele (suporta rollback)
select * from avizier; -- tabel gol
rollback; -- anulam stergerea
select * from avizier; -- datele au revenit


-- union example
select nume, prenume, 'Student' as tip from studenti
union
select nume, prenume, 'Angajat' as tip from staff;

-- intersect example
select s.id_student, s.nume 
from studenti s where lower(s.facultate) like '%cibernetica%'
intersect
select s.id_student, s.nume 
from studenti s 
join cazari z on s.id_student = z.id_student
join camere cm on z.id_camera = cm.id_camera
join camine c on cm.id_camin = c.id_camin
where lower(c.cod_camin) = 'moxa';

-- minus example
select id_student, nume, prenume
from studenti 
where forma_finantare = 'buget'
minus
select s.id_student, s.nume, s.prenume from studenti s 
join cazari z on s.id_student = z.id_student;

-- decode example
select nume, decode(sex, 'm', 'Masculin', 'f', 'Feminin', 'Nedefinit') as gen
from studenti
where rownum <= 5;

-- case example
select l.an_universitar, c.nume_camin, l.pret_taxa,
    case when l.pret_taxa < 300 then 'Ieftin' when l.pret_taxa in (300,500) then 'Mediu' else 'Scump' end as categorie_pret
from lista_preturi_camin l
join camine c on l.id_camin = c.id_camin;

-- string function
select upper(nume) as nume_mare, initcap(prenume) as prenume_corect, length(nume || prenume) as lungime_nume_complet
from studenti
where rownum <= 10;

-- data function
select s.nume, pc.data_start_contract, round(months_between(sysdate, pc.data_start_contract), 1) as luni_vechime
from staff s
join personal_camin pc on s.id_staff = pc.id_staff;

-- nvl function, doesnt return null emails because all students were defined with email
select nume, nvl(email, 'Nu are email setat') as contact
from studenti;

-- roommates of popescu andrei
select s.nume, s.prenume 
from studenti s
join cazari z on s.id_student = z.id_student
where z.id_camera = (
    select z2.id_camera from cazari z2 join studenti s2 on z2.id_student = s2.id_student where lower(s2.nume) = 'popescu' and lower(s2.prenume) = 'andrei'
) and s.nume != 'Popescu';

-- faculties with more than 10 students
select * from (
    select facultate, count(*) as nr_studenti from studenti group by facultate
) tabel_virtual where nr_studenti > 10;

-- over median price for accommodation check
select c.nume_camin, l.pret_taxa
from camine c
join lista_preturi_camin l on c.id_camin = l.id_camin
where l.pret_taxa > (select avg(pret_taxa) from lista_preturi_camin);

-- exists clause
select s.nume, s.prenume
from staff s
where exists (select 1 from plati_salarii p where p.id_staff = s.id_staff);

-- left join
select c.nume_camin, cm.nr_camera
from camine c
left outer join camere cm on c.id_camin = cm.id_camin
where cm.id_camera is null;

-- full outer join
select s.nume, f.suma_plata
from studenti s
full outer join cazari z on s.id_student = z.id_student
full outer join facturi_cazare f on z.id_cazare = f.id_cazare
where rownum <= 10;

-- group by & having
select facultate, count(*) as nr_studenti
from studenti
where forma_finantare = 'buget'
group by facultate
having count(*) > 3;

-- statistics of salaries
select min(salariu_baza) as minim, max(salariu_baza) as maxim, round(avg(salariu_baza), 2) as medie, sum(salariu_baza) as fond_salarii
from staff;

-- ranking employees by id
alter table staff add id_sef number;
update staff set id_sef = (select id_staff from staff where nume='Popescu' and rownum=1) where nume != 'Popescu';
commit;

select level, lpad(' ', 2*level) || nume || ' ' || prenume as organigrama, functie_baza
from staff
start with id_sef is null
connect by prior id_staff = id_sef;

-- analytics using dense_rank() : generations of students
select nume, prenume, an_inceput_studii, dense_rank() over (order by an_inceput_studii desc) as generatia
from studenti
where rownum <= 20;

-- count of invoices
select s.nume, f.luna, f.suma_plata, row_number() over (partition by s.id_student order by f.luna) as nr_factura
from facturi_cazare f
join cazari z on f.id_cazare = z.id_cazare
join studenti s on z.id_student = s.id_student;

-- rapport of students with accommodation and their monthly rent for October 2025
select initcap(s.nume) || ' ' || initcap(s.prenume) as student, c.nume_camin, cm.nr_camera, f.suma_plata || ' RON' as chirie_luna_curenta
from studenti s
join cazari z on s.id_student = z.id_student
join camere cm on z.id_camera = cm.id_camera
join camine c on cm.id_camin = c.id_camin
join facturi_cazare f on z.id_cazare = f.id_cazare
where f.luna = 10 and f.anul = 2025;

-- total income per dormitory for October 2025
select c.nume_camin, count(s.id_student) as numar_studenti_cazati, sum(f.suma_plata) as total_incasari_ron
from camine c
join camere cm on c.id_camin = cm.id_camin
join cazari z on cm.id_camera = z.id_camera
join studenti s on z.id_student = s.id_student
join facturi_cazare f on z.id_cazare = f.id_cazare
where f.luna = 10 and f.anul = 2025
group by c.nume_camin
order by total_incasari_ron desc;

-- how many free spots are left in each dormitory?
select c.nume_camin,
    (select sum(capacitate) from camere where id_camin = c.id_camin) as locuri_totale,
    count(z.id_cazare) as locuri_ocupate,
    (select sum(capacitate) from camere where id_camin = c.id_camin) - count(z.id_cazare) as locuri_libere
from camine c
left join camere cm on c.id_camin = cm.id_camin
left join cazari z on cm.id_camera = z.id_camera and z.status_cazare = 'activ'
group by c.id_camin, c.nume_camin
order by locuri_ocupate desc;

-- students per faculty category with accommodation
select case when lower(s.facultate) like '%cibernetica%' then 'CSIE' when lower(s.facultate) like '%fabiz%' then 'FABIZ' else 'Alte Facultati' end as categorie_facultate, count(s.id_student) as numar_studenti
from studenti s
join cazari z on s.id_student = z.id_student
where z.status_cazare = 'activ'
group by case when lower(s.facultate) like '%cibernetica%' then 'CSIE' when lower(s.facultate) like '%fabiz%' then 'FABIZ' else 'Alte Facultati' end;

-- salary ranking of employees for October 2025
select dense_rank() over (order by ps.salariu_final_net desc) as loc_clasament, initcap(s.nume) || ' ' || initcap(s.prenume) as angajat, s.functie_baza, c.nume_camin as loc_munca, ps.salariu_final_net as salariu_net
from plati_salarii ps
join staff s on ps.id_staff = s.id_staff
join personal_camin pc on s.id_staff = pc.id_staff
join camine c on pc.id_camin = c.id_camin
where ps.luna = 10
order by loc_clasament;

-- view example
create or replace view v_lista_publica_studenti as
select nume, prenume, facultate, specializare
from studenti
where status_student = 'activ';

select * from v_lista_publica_studenti where rownum <= 5;

-- index example
create index idx_nume_student on studenti(nume);

-- synonym example
create synonym tarife for lista_preturi_camin;
select * from tarife where rownum <= 2;

-- sequence example
select seq_facturi.currval from dual;
alter sequence seq_facturi increment by 10;

-- trigger example
create or replace trigger trg_securitate_salariu
before update of salariu_baza on staff
for each row
begin
    if :new.salariu_baza < :old.salariu_baza then
        raise_application_error(-20001, 'Eroare: Este ilegala scaderea salariului!');
    end if;
end;
/

-- trigger test - should raise an error, uncomment the unfollowing line to test
-- update staff set salariu_baza = 1000 where nume = 'Popescu';
