-- ==============================================================================
-- 1. CURATARE STRUCTURI ANTERIOARE (DROP)
-- ==============================================================================
BEGIN
    FOR i IN (SELECT table_name FROM user_tables WHERE table_name IN ('PLATI_SALARII', 'ANGAJAT_SPORURI', 'TIPURI_SPORURI', 'PERSONAL_CAMIN', 'STAFF', 'FACTURI_CAZARE', 'CAZARI', 'STUDENTI', 'LISTA_PRETURI_CAMIN', 'CAMERE', 'CAMINE', 'AVIZIER')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || i.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR i IN (SELECT sequence_name FROM user_sequences WHERE sequence_name = 'SEQ_FACTURI') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || i.sequence_name;
    END LOOP;
    FOR i IN (SELECT view_name FROM user_views WHERE view_name = 'V_LISTA_PUBLICA_STUDENTI') LOOP
        EXECUTE IMMEDIATE 'DROP VIEW ' || i.view_name;
    END LOOP;
    FOR i IN (SELECT synonym_name FROM user_synonyms WHERE synonym_name = 'TARIFE') LOOP
        EXECUTE IMMEDIATE 'DROP SYNONYM ' || i.synonym_name;
    END LOOP;
END;
/
-- ==============================================================================
-- 2. DDL BAZA (CREARE TABELE)
-- ==============================================================================
create table camine (
    id_camin number generated by default as identity,
    cod_camin varchar2(20) not null,
    nume_camin varchar2(100),
    adresa varchar2(200),
    if_mixt number(1) default 0,
    constraint pk_camine primary key (id_camin),
    constraint uq_cod_camin unique (cod_camin),
    constraint ck_mixt check (if_mixt in (0, 1))
);

create table lista_preturi_camin (
    id_pret number generated by default as identity,
    id_camin number not null,
    an_universitar varchar2(9) not null,
    pret_buget number(10, 2) not null,
    pret_taxa number(10, 2) not null,
    constraint pk_lista_preturi primary key (id_pret),
    constraint fk_pret_camin foreign key (id_camin) references camine(id_camin),
    constraint uq_pret_an_camin unique (id_camin, an_universitar)
);

create table camere (
    id_camera number generated by default as identity,
    id_camin number not null,
    nr_camera varchar2(10) not null,
    etaj number(2),
    capacitate number(2) not null,
    constraint pk_camere primary key (id_camera),
    constraint fk_camere_camin foreign key (id_camin) references camine(id_camin),
    constraint uq_camera_in_camin unique (id_camin, nr_camera),
    constraint ck_capacitate_pozitiva check (capacitate > 0)
);

create table studenti (
    id_student number generated by default as identity,
    nr_matricol varchar2(20) not null,
    nume varchar2(50) not null,
    prenume varchar2(50) not null,
    cnp varchar2(13) not null,
    sex varchar2(1),
    facultate varchar2(100),
    specializare varchar2(100),
    an_curent varchar2(2),
    an_inceput_studii number(4),
    forma_finantare varchar2(20) not null,
    status_student varchar2(20) default 'activ',
    email varchar2(150),
    telefon varchar2(15),
    constraint pk_studenti primary key (id_student),
    constraint uq_matricol unique (nr_matricol),
    constraint uq_cnp unique (cnp),
    constraint ck_finantare check (forma_finantare in ('buget', 'taxa', 'social')),
    constraint ck_sex check (sex in ('m', 'f')),
    constraint ck_an_curent check (an_curent in ('1', '2', '3', 'M1', 'M2'))
);

create table cazari (
    id_cazare number generated by default as identity,
    id_student number not null,
    id_camera number not null,
    an_universitar varchar2(9) not null,
    data_start date default sysdate,
    data_final date,
    status_cazare varchar2(20) default 'activ',
    constraint pk_cazari primary key (id_cazare),
    constraint fk_cazari_student foreign key (id_student) references studenti(id_student),
    constraint fk_cazari_camera foreign key (id_camera) references camere(id_camera),
    constraint ck_date_valide check (data_final >= data_start)
);

create table facturi_cazare (
    id_factura number,
    id_cazare number not null,
    luna number(2) not null,
    anul number(4) not null,
    suma_plata number(10, 2) not null,
    data_emitere date,
    status_factura varchar2(20) default 'neplatit',
    constraint pk_facturi primary key (id_factura),
    constraint fk_facturi_cazare foreign key (id_cazare) references cazari(id_cazare),
    constraint ck_luna check (luna between 1 and 12),
    constraint ck_suma_pozitiva check (suma_plata > 0)
);

create table staff (
    id_staff number generated by default as identity,
    nume varchar2(50) not null,
    prenume varchar2(50) not null,
    cnp varchar2(13) not null,
    functie_baza varchar2(50),
    salariu_baza number(10, 2),
    email_institutional varchar2(100),
    id_sef number,
    constraint pk_staff primary key (id_staff),
    constraint uq_cnp_staff unique (cnp),
    constraint ck_salariu_minim check (salariu_baza >= 2500)
);

create table tipuri_sporuri (
    id_spor number generated by default as identity,
    nume_spor varchar2(50) not null,
    procent number(5, 2) not null,
    constraint pk_sporuri primary key (id_spor)
);

create table angajat_sporuri (
    id_asoc number generated by default as identity,
    id_staff number not null,
    id_spor number not null,
    constraint pk_angajat_spor primary key (id_asoc),
    constraint fk_asoc_staff foreign key (id_staff) references staff(id_staff),
    constraint fk_asoc_spor foreign key (id_spor) references tipuri_sporuri(id_spor)
);

create table plati_salarii (
    id_plata number generated by default as identity,
    id_staff number not null,
    luna number(2) not null,
    anul number(4) not null,
    data_platii date,
    salariu_baza_istoric number(10, 2),
    total_sporuri_lei number(10, 2),
    salariu_final_net number(10, 2),
    constraint pk_plati primary key (id_plata),
    constraint fk_plati_staff foreign key (id_staff) references staff(id_staff)
);

create table personal_camin (
    id_contract number generated by default as identity,
    id_staff number not null,
    id_camin number not null,
    data_start_contract date default sysdate,
    constraint pk_personal_camin primary key (id_contract),
    constraint fk_pers_staff foreign key (id_staff) references staff(id_staff),
    constraint fk_pers_camin foreign key (id_camin) references camine(id_camin)
);

create table avizier (
    id_anunt number,
    mesaj varchar2(100)
);
-- ==============================================================================
-- 3. OBIECTE AUXILIARE (SECVENTE, VIEW, INDEX, SYNONYM)
-- ==============================================================================
create sequence seq_facturi start with 1000 increment by 1;

create or replace view v_lista_publica_studenti as
select nume, prenume, facultate, specializare
from studenti
where status_student = 'activ';

create index idx_nume_student on studenti(nume);

create or replace synonym tarife for lista_preturi_camin;
-- ==============================================================================
-- 4. DML (INSERARE DATE INITIALE SI ACTUALIZARI)
-- ==============================================================================

insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('moxa', 'Complex Moxa D', 'Mihail Moxa 11', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a6', 'Belvedere Nou A6', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a7', 'Belvedere Nou A7', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a8', 'Belvedere Nou A8', 'Chibzuintei 2', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('tei', 'Complex Tei C1', 'Lacul Tei 116', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a1', 'Belvedere Vechi A1', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a2', 'Belvedere Vechi A2', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a3', 'Belvedere Vechi A3', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('belv-a4', 'Belvedere Vechi A4', 'Cristian Pascal 27', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('agro-c1', 'Agronomie C1', 'Marasti 59', 0);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('agro-c2', 'Agronomie C2', 'Marasti 59', 0); 
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('occid', 'Occidentului', 'Occidentului 7', 1);
insert into camine (cod_camin, nume_camin, adresa, if_mixt) values ('vitan', 'Vitan Center', 'Energeticienilor 9', 1);
select * from camine;

insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 200, 400 
from camine 
where lower(nume_camin) like '%moxa%' or lower(nume_camin) like '%belvedere nou%' or lower(nume_camin) like '%tei%';

insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 150, 290 
from camine 
where lower(nume_camin) like '%belvedere vechi%' or lower(nume_camin) like '%agronomie%' or lower(nume_camin) like '%vitan%';

insert into lista_preturi_camin (id_camin, an_universitar, pret_buget, pret_taxa)
select id_camin, '2024-2025', 650, 800 
from camine 
where lower(nume_camin) like '%occidentului%';
select c.nume_camin, l.pret_buget, l.pret_taxa 
from lista_preturi_camin l 
join camine c on l.id_camin = c.id_camin
order by l.pret_buget desc;

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 4
from camine c
cross join (select level as etaj from dual connect by level <= 6) 
cross join (select level as cam from dual connect by level <= 8)  
where lower(c.nume_camin) like '%moxa%' or lower(c.nume_camin) like '%belvedere nou%';

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 4
from camine c
cross join (select level + 3 as etaj from dual connect by level <= 2) 
cross join (select level as cam from dual connect by level <= 20)
where lower(c.nume_camin) like '%tei%';

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, case when lower(c.nume_camin) like '%agronomie%' then 3 else 2 end
from camine c
cross join (select level as etaj from dual connect by level <= 2) 
cross join (select level as cam from dual connect by level <= 15)
where lower(c.nume_camin) like '%belvedere vechi%' or lower(c.nume_camin) like '%agronomie%';

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 2
from camine c
cross join (select level as etaj from dual connect by level <= 6)
cross join (select level as cam from dual connect by level <= 5)
where lower(c.nume_camin) like '%occidentului%';

insert into camere (id_camin, nr_camera, etaj, capacitate)
select c.id_camin, etaj || lpad(cam, 2, '0'), etaj, 2
from camine c
cross join (select level as etaj from dual connect by level <= 4)
cross join (select level as cam from dual connect by level <= 10)
where lower(c.nume_camin) like '%vitan%';
--query check for camere
select c.nume_camin, count(*) as numar_camere, sum(cam.capacitate) as total_locuri
from camere cam
join camine c on cam.id_camin = c.id_camin
group by c.nume_camin
order by c.nume_camin;

insert into studenti (nr_matricol, nume, prenume, cnp, sex, facultate, specializare, an_curent, an_inceput_studii, forma_finantare, email)
select 
    lower(substr(fac_code, 1, 3)) || '_' || to_char(rownum + 100),
    initcap(nume_real),
    initcap(prenume_real),
    (case sex_real when 'm' then 5 else 6 end) || substr(to_char(an_start - 19), 3, 2) || '0000' || to_char(rownum + 1000),
    sex_real,
    nume_facultate,
    nume_specializare,
    case when (2025 - an_start + 1) = 1 then '1' when (2025 - an_start + 1) = 2 then '2' when (2025 - an_start + 1) = 3 then '3' when (2025 - an_start + 1) = 4 then 'M1' else 'M2' end,
    an_start,
    'buget',
    email_real
from (
    select nume_real, prenume_real, sex_real, an_start, email_real,
        case mod(rownum, 26) when 0 then 'FABIZ' when 1 then 'FABIZ' when 2 then 'FABIZ' when 3 then 'AMP' when 4 then 'AMP' when 5 then 'BT' when 6 then 'BT' when 7 then 'CSIE' when 8 then 'CSIE' when 9 then 'CSIE' when 10 then 'CIG' when 11 then 'CIG' when 12 then 'DREPT' when 13 then 'ECA' when 14 then 'ECA' when 15 then 'EAM' when 16 then 'EAM' when 17 then 'FABBV' when 18 then 'FABBV' when 19 then 'MAN' when 20 then 'MAN' when 21 then 'MK' when 22 then 'MK' when 23 then 'REI' when 24 then 'REI' else 'BBS' end as fac_code,
        case mod(rownum, 26) when 0 then 'Administrarea Afacerilor (FABIZ)' when 1 then 'Administrarea Afacerilor (FABIZ)' when 2 then 'Administrarea Afacerilor (FABIZ)' when 3 then 'Administratie si Management Public' when 4 then 'Administratie si Management Public' when 5 then 'Business si Turism' when 6 then 'Business si Turism' when 7 then 'Cibernetica, Statistica si Informatica' when 8 then 'Cibernetica, Statistica si Informatica' when 9 then 'Cibernetica, Statistica si Informatica' when 10 then 'Contabilitate si Informatica de Gestiune' when 11 then 'Contabilitate si Informatica de Gestiune' when 12 then 'Drept' when 13 then 'Economie si Comunicare in Afaceri' when 14 then 'Economie si Comunicare in Afaceri' when 15 then 'Economie Agroalimentara si a Mediului' when 16 then 'Economie Agroalimentara si a Mediului' when 17 then 'Finante, Asigurari, Banci si Burse' when 18 then 'Finante, Asigurari, Banci si Burse' when 19 then 'Management' when 20 then 'Management' when 21 then 'Marketing' when 22 then 'Marketing' when 23 then 'Relatii Economice Internationale' when 24 then 'Relatii Economice Internationale' else 'Bucharest Business School' end as nume_facultate,
        case mod(rownum, 26) when 0 then 'Administrarea Afacerilor (Engleza)' when 1 then 'Administrarea Afacerilor (Germana)' when 2 then 'Administrarea Afacerilor (Franceza)' when 3 then 'Administratie Publica' when 4 then 'Resurse Umane' when 5 then 'Business si Turism' when 6 then 'Merceologie si Management' when 7 then 'Informatica Economica' when 8 then 'Cibernetica Economica' when 9 then 'Statistica si Previziune' when 10 then 'Contabilitate si Info de Gestiune' when 11 then 'Contabilitate si Audit' when 12 then 'Drept' when 13 then 'Comunicare in Afaceri' when 14 then 'Economie Generala' when 15 then 'Economie Agroalimentara' when 16 then 'Ecologie si Protectia Mediului' when 17 then 'Finante si Banci' when 18 then 'Finante si Banci (Engleza)' when 19 then 'Management' when 20 then 'Management (Engleza)' when 21 then 'Marketing' when 22 then 'Marketing (Engleza)' when 23 then 'Economie si Afaceri Int.' when 24 then 'Limbi Moderne Aplicate' else 'MBA Romano-Canadian' end as nume_specializare
    from (
        select 'popescu' nume_real, 'andrei' prenume_real, 'm' sex_real, 2025 an_start, 'popescuandrei25@stud.ase.ro' email_real from dual union all
        select 'ionescu', 'maria', 'f', 2021, 'ionescumaria21@stud.ase.ro' from dual union all
        select 'radu', 'vlad', 'm', 2024, 'raduvlad24@stud.ase.ro' from dual union all
        select 'dumitru', 'elena', 'f', 2023, 'dumitruelena23@stud.ase.ro' from dual union all
        select 'stoica', 'george', 'm', 2022, 'stoicageorge22@stud.ase.ro' from dual union all
        select 'stan', 'ioana', 'f', 2025, 'stanioana25@stud.ase.ro' from dual union all
        select 'gheorghe', 'david', 'm', 2021, 'gheorghedavid21@stud.ase.ro' from dual union all
        select 'mihai', 'alexandru', 'm', 2024, 'mihaialexandru24@stud.ase.ro' from dual union all
        select 'constantin', 'ana', 'f', 2023, 'constantinana23@stud.ase.ro' from dual union all
        select 'enache', 'ionut', 'm', 2022, 'enacheionut22@stud.ase.ro' from dual union all
        select 'vasilescu', 'mihai', 'm', 2025, 'vasilescumihai25@stud.ase.ro' from dual union all
        select 'marin', 'andreea', 'f', 2024, 'marinandreea24@stud.ase.ro' from dual union all
        select 'dinu', 'stefan', 'm', 2021, 'dinustefan21@stud.ase.ro' from dual union all
        select 'tudor', 'gabriel', 'm', 2022, 'tudorgabriel22@stud.ase.ro' from dual union all
        select 'nistor', 'cristina', 'f', 2023, 'nistorcristina23@stud.ase.ro' from dual union all
        select 'florea', 'robert', 'm', 2025, 'florearobert25@stud.ase.ro' from dual union all
        select 'mocanu', 'diana', 'f', 2024, 'mocanudiana24@stud.ase.ro' from dual union all
        select 'oprea', 'daniel', 'm', 2021, 'opreadaniel21@stud.ase.ro' from dual union all
        select 'barbu', 'alexia', 'f', 2022, 'barbualexia22@stud.ase.ro' from dual union all
        select 'neagu', 'cosmin', 'm', 2023, 'neagucosmin23@stud.ase.ro' from dual union all
        select 'popa', 'stefan', 'm', 2025, 'popastefan25@stud.ase.ro' from dual union all
        select 'rusu', 'denisa', 'f', 2024, 'rusudenisa24@stud.ase.ro' from dual union all
        select 'munteanu', 'razvan', 'm', 2021, 'munteanurazvan21@stud.ase.ro' from dual union all
        select 'matei', 'catalina', 'f', 2022, 'mateicatalina22@stud.ase.ro' from dual union all
        select 'serban', 'eduard', 'm', 2023, 'serbaneduard23@stud.ase.ro' from dual union all
        select 'lazar', 'bianca', 'f', 2025, 'lazarbianca25@stud.ase.ro' from dual union all
        select 'moldovan', 'florin', 'm', 2024, 'moldovanflorin24@stud.ase.ro' from dual union all
        select 'vasile', 'teodora', 'f', 2021, 'vasileteodora21@stud.ase.ro' from dual union all
        select 'dragan', 'alexandra', 'f', 2022, 'draganalexandra22@stud.ase.ro' from dual union all
        select 'sandu', 'cristian', 'm', 2023, 'sanducristian23@stud.ase.ro' from dual union all
        select 'voinea', 'laura', 'f', 2025, 'voinealaura25@stud.ase.ro' from dual union all
        select 'albu', 'adrian', 'm', 2024, 'albuadrian24@stud.ase.ro' from dual union all
        select 'diaconu', 'georgiana', 'f', 2021, 'diaconugeorgiana21@stud.ase.ro' from dual union all
        select 'petrescu', 'victor', 'm', 2022, 'petrescuvictor22@stud.ase.ro' from dual union all
        select 'ciobanu', 'alina', 'f', 2023, 'ciobanualina23@stud.ase.ro' from dual union all
        select 'toma', 'marius', 'm', 2025, 'tomamarius25@stud.ase.ro' from dual union all
        select 'pavel', 'andrada', 'f', 2024, 'pavelandrada24@stud.ase.ro' from dual union all
        select 'cristea', 'rares', 'm', 2021, 'cristearares21@stud.ase.ro' from dual union all
        select 'florescu', 'monica', 'f', 2022, 'florescumonica22@stud.ase.ro' from dual union all
        select 'dobre', 'silviu', 'm', 2023, 'dobresilviu23@stud.ase.ro' from dual union all
        select 'ungureanu', 'camelia', 'f', 2025, 'ungureanucamelia25@stud.ase.ro' from dual union all
        select 'ionescu', 'dan', 'm', 2024, 'ionescudan24@stud.ase.ro' from dual union all
        select 'dumitrache', 'ioana', 'f', 2021, 'dumitracheioana21@stud.ase.ro' from dual union all
        select 'avram', 'bogdan', 'm', 2022, 'avrambogdan22@stud.ase.ro' from dual union all
        select 'nedelea', 'valentina', 'f', 2023, 'nedeleavalentina23@stud.ase.ro' from dual union all
        select 'stanciu', 'mihai', 'm', 2025, 'stanciumihai25@stud.ase.ro' from dual union all
        select 'coman', 'larisa', 'f', 2024, 'comanlarisa24@stud.ase.ro' from dual union all
        select 'apostol', 'paul', 'm', 2021, 'apostolpaul21@stud.ase.ro' from dual union all
        select 'manole', 'eliza', 'f', 2022, 'manoleeliza22@stud.ase.ro' from dual union all
        select 'negru', 'sebastian', 'm', 2023, 'negrusebastian23@stud.ase.ro' from dual union all
        select 'preda', 'antonia', 'f', 2025, 'predaantonia25@stud.ase.ro' from dual union all
        select 'voicu', 'sergiu', 'm', 2024, 'voicusergiu24@stud.ase.ro' from dual union all
        select 'cojocaru', 'madalina', 'f', 2021, 'cojocarumadalina21@stud.ase.ro' from dual union all
        select 'badea', 'lucian', 'm', 2022, 'badealuciau22@stud.ase.ro' from dual union all
        select 'ionita', 'marian', 'm', 2023, 'ionitamarian23@stud.ase.ro' from dual union all
        select 'olaru', 'rebeca', 'f', 2025, 'olarurebeca25@stud.ase.ro' from dual union all
        select 'tanase', 'costin', 'm', 2024, 'tanasecostin24@stud.ase.ro' from dual union all
        select 'danila', 'marilena', 'f', 2021, 'danilamarilena21@stud.ase.ro' from dual union all
        select 'filip', 'alex', 'm', 2022, 'filipalex22@stud.ase.ro' from dual union all
        select 'simion', 'robert', 'm', 2023, 'simionrobert23@stud.ase.ro' from dual union all
        select 'grosu', 'daria', 'f', 2025, 'grosudaria25@stud.ase.ro' from dual union all
        select 'lazarescu', 'matei', 'm', 2024, 'lazarescumatei24@stud.ase.ro' from dual union all
        select 'marcu', 'adriana', 'f', 2021, 'marcuadriana21@stud.ase.ro' from dual union all
        select 'parvu', 'gabriel', 'm', 2022, 'parvugabriel22@stud.ase.ro' from dual union all
        select 'rotaru', 'cosmina', 'f', 2023, 'rotarucosmina23@stud.ase.ro' from dual union all
        select 'teodorescu', 'dorin', 'm', 2025, 'teodorescudorin25@stud.ase.ro' from dual union all
        select 'maria', 'nicoleta', 'f', 2024, 'marianicoleta24@stud.ase.ro' from dual union all
        select 'ifrim', 'sorin', 'm', 2021, 'ifrimsorin21@stud.ase.ro' from dual union all
        select 'alex', 'elena', 'f', 2022, 'alexelena22@stud.ase.ro' from dual union all
        select 'balan', 'petru', 'm', 2023, 'balanpetru23@stud.ase.ro' from dual union all
        select 'zamfir', 'raluca', 'f', 2025, 'zamfirraluca25@stud.ase.ro' from dual union all
        select 'niculae', 'cristi', 'm', 2024, 'niculaecristi24@stud.ase.ro' from dual union all
        select 'calin', 'beatrice', 'f', 2021, 'calinbeatrice21@stud.ase.ro' from dual union all
        select 'tamas', 'vladimir', 'm', 2022, 'tamasvladimir22@stud.ase.ro' from dual union all
        select 'david', 'sonia', 'f', 2023, 'davidsonia23@stud.ase.ro' from dual union all
        select 'ghenghea', 'ovidiu', 'm', 2025, 'ghengheaovidiu25@stud.ase.ro' from dual union all
        select 'iancu', 'emilia', 'f', 2024, 'iancuemilia24@stud.ase.ro' from dual union all
        select 'moculescu', 'horia', 'm', 2021, 'moculescuhoria21@stud.ase.ro' from dual union all
        select 'trandafir', 'sofia', 'f', 2022, 'trandafirsofia22@stud.ase.ro' from dual union all
        select 'costea', 'claudiu', 'm', 2023, 'costeaclaudiu23@stud.ase.ro' from dual union all
        select 'lungu', 'tiberiu', 'm', 2025, 'lungutiberiu25@stud.ase.ro' from dual union all
        select 'burlacu', 'iulia', 'f', 2024, 'burlacuiulia24@stud.ase.ro' from dual union all
        select 'cretu', 'vasile', 'm', 2021, 'cretuvasile21@stud.ase.ro' from dual union all
        select 'arsene', 'octavian', 'm', 2022, 'arseneoctavian22@stud.ase.ro' from dual union all
        select 'ignat', 'patricia', 'f', 2023, 'ignatpatricia23@stud.ase.ro' from dual union all
        select 'savu', 'mircea', 'm', 2025, 'savumircea25@stud.ase.ro' from dual union all
        select 'milea', 'florina', 'f', 2024, 'mileaflorina24@stud.ase.ro' from dual union all
        select 'luca', 'andrei', 'm', 2021, 'lucaandrei21@stud.ase.ro' from dual union all
        select 'olteanu', 'carmen', 'f', 2022, 'olteanucarmen22@stud.ase.ro' from dual union all
        select 'miron', 'liviu', 'm', 2023, 'mironliviu23@stud.ase.ro' from dual union all
        select 'suciu', 'stephanie', 'f', 2025, 'suciustephanie25@stud.ase.ro' from dual union all
        select 'pascu', 'dorin', 'm', 2024, 'pascudorin24@stud.ase.ro' from dual union all
        select 'vintila', 'anca', 'f', 2021, 'vintilaanca21@stud.ase.ro' from dual union all
        select 'roman', 'felix', 'm', 2022, 'romanfelix22@stud.ase.ro' from dual union all
        select 'zaharia', 'emanuel', 'm', 2023, 'zahariaemanuel23@stud.ase.ro' from dual union all
        select 'anton', 'irina', 'f', 2025, 'antonirina25@stud.ase.ro' from dual union all
        select 'bordea', 'albert', 'm', 2024, 'bordeaalbert24@stud.ase.ro' from dual union all
        select 'stroe', 'ilinca', 'f', 2021, 'stroeilinca21@stud.ase.ro' from dual union all
        select 'codreanu', 'filip', 'm', 2022, 'codreanufilip22@stud.ase.ro' from dual
    )
);
select specializare, count(*) from studenti group by specializare order by 1;

insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Andrei', 'Lenuta', '2800101123456', 'Administrator', 4500, 'andrei.lenuta@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Bardac', 'Geta', '2810202123456', 'Administrator', 4500, 'bardac.geta@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Iosif', 'Alexandru', '1790303123456', 'Administrator', 4200, 'iosif.alexandru@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Padure', 'Andrei', '1850404123456', 'Administrator', 4000, 'padure.andrei@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Ghiur', 'Silvia', '2750505123456', 'Administrator', 4100, 'ghiur.silvia@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Popescu', 'Constantin', '1600606123456', 'Administrator', 5000, 'popescu.constantin@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza, email_institutional) values ('Vargatiuc', 'Mihaela', '2820707123456', 'Administrator', 4300, 'mihaela.vargatiuc@ase.ro');
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza) values ('Ionescu', 'Vasile', '1700101999999', 'Instalator', 3500);
insert into staff (nume, prenume, cnp, functie_baza, salariu_baza) values ('Popa', 'Maria', '2700101888888', 'Femeie de Serviciu', 2800);

insert into tipuri_sporuri (nume_spor, procent) values ('Spor Vechime', 0.15);
insert into tipuri_sporuri (nume_spor, procent) values ('Spor Conducere', 0.25);
insert into tipuri_sporuri (nume_spor, procent) values ('Spor Toxicitate', 0.10);

insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where s.functie_baza = 'Administrator' and t.nume_spor = 'Spor Conducere';
insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where t.nume_spor = 'Spor Vechime';
insert into angajat_sporuri (id_staff, id_spor) select s.id_staff, t.id_spor from staff s, tipuri_sporuri t where s.functie_baza = 'Instalator' and t.nume_spor = 'Spor Toxicitate';

insert into personal_camin (id_staff, id_camin, data_start_contract)
select s.id_staff, c.id_camin, add_months(sysdate, -round(dbms_random.value(1, 60)))
from staff s
join camine c on (s.nume = 'Andrei' and c.cod_camin = 'moxa') or (s.nume = 'Bardac' and c.cod_camin = 'belv-a6') or (s.nume = 'Iosif' and c.cod_camin = 'tei') or (s.nume = 'Padure' and c.cod_camin = 'belv-a1') or (s.nume = 'Ghiur' and c.cod_camin = 'agro-c1') or (s.nume = 'Popescu' and c.cod_camin = 'occid') or (s.nume = 'Vargatiuc' and c.cod_camin = 'vitan');

insert into cazari (id_student, id_camera, an_universitar, status_cazare)
select s.id_student, match.id_camera, '2024-2025', 'activ'
from studenti s
join (
    select st.id_student, cm.id_camera, row_number() over (partition by st.id_student order by dbms_random.value) as rn
    from studenti st
    join camine k on 1=1 join camere cm on k.id_camin = cm.id_camin
    where st.sex = 'f' and (k.if_mixt = 1 or k.nume_camin like '%Fete%' or k.cod_camin in ('belv-a1', 'belv-a2', 'belv-a3', 'agro-c1'))
) match on s.id_student = match.id_student
where match.rn = 1;

insert into cazari (id_student, id_camera, an_universitar, status_cazare)
select s.id_student, match.id_camera, '2024-2025', 'activ'
from studenti s
join (
    select st.id_student, cm.id_camera, row_number() over (partition by st.id_student order by dbms_random.value) as rn
    from studenti st
    join camine k on 1=1 join camere cm on k.id_camin = cm.id_camin
    where st.sex = 'm' and (k.if_mixt = 1 or k.nume_camin like '%Baieti%' or k.cod_camin in ('belv-a4', 'agro-c2')) and cm.id_camera not in (select id_camera from cazari)
) match on s.id_student = match.id_student
where match.rn = 1;
select c.id_camera, count(distinct s.sex) as mix_sex
from cazari c
join studenti s on c.id_student = s.id_student
group by c.id_camera
having count(distinct s.sex) > 1;
select initcap(s.nume) || ' ' || initcap(s.prenume) as student, s.sex, k.nume_camin, cm.nr_camera
from cazari z
join studenti s on z.id_student = s.id_student
join camere cm on z.id_camera = cm.id_camera
join camine k on cm.id_camin = k.id_camin
order by k.nume_camin, cm.nr_camera;

insert into facturi_cazare (id_factura, id_cazare, luna, anul, suma_plata, data_emitere, status_factura)
select seq_facturi.nextval, z.id_cazare, extract(month from calendar.data_luna), extract(year from calendar.data_luna), case when s.forma_finantare = 'buget' then p.pret_buget else p.pret_taxa end, calendar.data_luna, 'neplatit'
from cazari z
join studenti s on z.id_student = s.id_student
join camere cm on z.id_camera = cm.id_camera
join lista_preturi_camin p on cm.id_camin = p.id_camin
cross join (select add_months(to_date('01-09-2025', 'dd-mm-yyyy'), level - 1) as data_luna from dual connect by level <= 10) calendar;

insert into plati_salarii (id_staff, luna, anul, data_platii, salariu_baza_istoric, total_sporuri_lei, salariu_final_net)
select s.id_staff, cal.luna, 2025, to_date('25-' || lpad(cal.luna, 2, '0') || '-2025', 'dd-mm-yyyy'), s.salariu_baza, round(s.salariu_baza * (select nvl(sum(ts.procent), 0) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff), 2), round(s.salariu_baza + (s.salariu_baza * (select nvl(sum(ts.procent), 0) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff)), 2)
from staff s
cross join (select level as luna from dual connect by level <= 12) cal;

commit;
select initcap(s.nume) || ' ' || initcap(s.prenume) as angajat, s.functie_baza, p.luna, p.salariu_baza_istoric as baza,
    (select listagg(ts.nume_spor || ' (' || (ts.procent*100) || '%)', ', ') within group (order by ts.nume_spor) from angajat_sporuri asoc join tipuri_sporuri ts on asoc.id_spor = ts.id_spor where asoc.id_staff = s.id_staff) as lista_sporuri,
    p.total_sporuri_lei as valoare_spor, p.salariu_final_net as total_incasat
from plati_salarii p
join staff s on p.id_staff = s.id_staff
where p.luna = 10 
order by p.salariu_final_net desc;
update staff set salariu_baza = salariu_baza * 1.1 where functie_baza = 'Administrator';
update studenti set telefon = '0722123456' where nume = 'Popescu' and prenume = 'Andrei';
commit;

-- ==============================================================================
-- 5. PACHETE PL/SQL
-- ==============================================================================
create or replace package pkg_dorm_finance as
    type t_student_rec is record (
        id_student studenti.id_student%type,
        full_name varchar2(100),
        total_debt number
    );
    type t_student_table is table of t_student_rec;

    function get_student_debt(p_id_student in studenti.id_student%type) return number;
    function get_top_debtors(p_limit in number) return t_student_table;

    procedure generate_monthly_invoices(p_month in number, p_year in number);
    procedure apply_penalties(p_percentage in number, p_month in number, p_year in number);
end pkg_dorm_finance;
/

create or replace package body pkg_dorm_finance as

    function get_student_debt(p_id_student in studenti.id_student%type) return number is
        v_debt number := 0;
        v_exists number;
        e_invalid_student exception;
    begin
        select count(*) into v_exists from studenti where id_student = p_id_student;
        if v_exists = 0 then
            raise e_invalid_student;
        end if;

        select nvl(sum(f.suma_plata), 0) into v_debt
        from facturi_cazare f
        join cazari c on f.id_cazare = c.id_cazare
        where c.id_student = p_id_student and f.status_factura = 'neplatit';
        
        return v_debt;
    exception
        when e_invalid_student then
            dbms_output.put_line('Error: The student with ID ' || p_id_student || ' does not exist.');
            return -1;
        when others then
            dbms_output.put_line('Unexpected error: ' || sqlerrm);
            return -1;
    end get_student_debt;

    function get_top_debtors(p_limit in number) return t_student_table is
        v_debtors t_student_table := t_student_table(); 
        
        cursor c_debtors is
            select s.id_student, s.nume || ' ' || s.prenume, nvl(sum(f.suma_plata), 0)
            from studenti s
            join cazari c on s.id_student = c.id_student
            join facturi_cazare f on c.id_cazare = f.id_cazare
            where f.status_factura = 'neplatit'
            group by s.id_student, s.nume, s.prenume
            order by sum(f.suma_plata) desc;
            
        v_rec t_student_rec;
        v_counter number := 1;
    begin
        open c_debtors;
        loop
            fetch c_debtors into v_rec;
            exit when c_debtors%notfound or v_counter > p_limit;
            
            v_debtors.extend;
            v_debtors(v_debtors.last) := v_rec;
            v_counter := v_counter + 1;
        end loop;
        close c_debtors;
        
        return v_debtors;
    end get_top_debtors;

    procedure generate_monthly_invoices(p_month in number, p_year in number) is
        v_counter number := 0;
        v_applicable_price number;
    begin
        for rec in (
            select c.id_cazare, s.forma_finantare, cm.id_camin, c.an_universitar
            from cazari c
            join studenti s on c.id_student = s.id_student
            join camere cm on c.id_camera = cm.id_camera
            where c.status_cazare = 'activ'
        ) loop
            select case when rec.forma_finantare = 'buget' then pret_buget else pret_taxa end 
            into v_applicable_price
            from lista_preturi_camin
            where id_camin = rec.id_camin and an_universitar = rec.an_universitar;

            insert into facturi_cazare (id_factura, id_cazare, luna, anul, suma_plata, data_emitere, status_factura)
            values (seq_facturi.nextval, rec.id_cazare, p_month, p_year, v_applicable_price, sysdate, 'neplatit');
            
            v_counter := v_counter + 1;
        end loop;
        
        dbms_output.put_line(v_counter || ' new invoices have been generated.');
        commit;
    exception
        when others then
            rollback;
            dbms_output.put_line('Error processing invoices: ' || sqlerrm);
    end generate_monthly_invoices;

    procedure apply_penalties(p_percentage in number, p_month in number, p_year in number) is
        cursor c_overdue is
            select id_factura, suma_plata 
            from facturi_cazare 
            where status_factura = 'neplatit' and luna = p_month and anul = p_year
            for update of suma_plata nowait;
        v_affected number := 0;
    begin
        for rec in c_overdue loop
            update facturi_cazare
            set suma_plata = suma_plata + (suma_plata * p_percentage / 100)
            where current of c_overdue;
            v_affected := v_affected + 1;
        end loop;
        commit;
        dbms_output.put_line('Penalties have been applied to ' || v_affected || ' invoices.');
    exception
        when others then
            rollback;
            dbms_output.put_line('Error applying penalties: ' || sqlerrm);
    end apply_penalties;

end pkg_dorm_finance;
/

create or replace package pkg_dorm_admin as
    type t_dorm_stats is record (total_capacity number, occupied_beds number, available_beds number);

    function get_room_availability(p_room_id in camere.id_camera%type) return number;
    function get_dorm_stats(p_dorm_id in camine.id_camin%type) return t_dorm_stats;

    procedure assign_student(p_student_id in studenti.id_student%type, p_dorm_code in varchar2);
    procedure clear_accommodations(p_academic_year in varchar2);
end pkg_dorm_admin;
/

create or replace package body pkg_dorm_admin as

    function get_room_availability(p_room_id in camere.id_camera%type) return number is
        v_capacity number;
        v_occupants number;
    begin
        select capacitate into v_capacity from camere where id_camera = p_room_id;
        select count(*) into v_occupants from cazari where id_camera = p_room_id and status_cazare = 'activ';
        return (v_capacity - v_occupants);
    exception
        when no_data_found then
            return -1;
    end get_room_availability;

    function get_dorm_stats(p_dorm_id in camine.id_camin%type) return t_dorm_stats is
        v_stats t_dorm_stats;
    begin
        select nvl(sum(capacitate), 0) into v_stats.total_capacity 
        from camere where id_camin = p_dorm_id;
        
        select count(cz.id_cazare) into v_stats.occupied_beds 
        from cazari cz
        join camere cm on cz.id_camera = cm.id_camera
        where cm.id_camin = p_dorm_id and cz.status_cazare = 'activ';
        
        v_stats.available_beds := v_stats.total_capacity - v_stats.occupied_beds;
        return v_stats;
    end get_dorm_stats;

    procedure assign_student(p_student_id in studenti.id_student%type, p_dorm_code in varchar2) is
        v_available_room camere.id_camera%type;
        e_no_spots exception;
    begin
        select cm.id_camera into v_available_room
        from camere cm
        join camine c on cm.id_camin = c.id_camin
        where c.cod_camin = lower(p_dorm_code)
          and pkg_dorm_admin.get_room_availability(cm.id_camera) > 0
          and rownum = 1;
          
        insert into cazari (id_student, id_camera, an_universitar, data_start, status_cazare)
        values (p_student_id, v_available_room, '2024-2025', sysdate, 'activ');
        
        dbms_output.put_line('The student was successfully assigned to a room.');
        commit;
    exception
        when no_data_found then
            dbms_output.put_line('Error: No available spots in the dormitory ' || p_dorm_code);
    end assign_student;

    procedure clear_accommodations(p_academic_year in varchar2) is
        cursor c_accommodations is
            select id_cazare from cazari 
            where an_universitar = p_academic_year and status_cazare = 'activ';
        v_counter number := 0;
    begin
        for rec in c_accommodations loop
            update cazari 
            set status_cazare = 'inactiv', data_final = sysdate 
            where id_cazare = rec.id_cazare;
            
            v_counter := v_counter + 1;
        end loop;
        commit;
        dbms_output.put_line(v_counter || ' accommodations have been cleared for the academic year ' || p_academic_year);
    end clear_accommodations;

end pkg_dorm_admin;
/

-- ==============================================================================
-- 6. SUBPROGRAME INDEPENDENTE
-- ==============================================================================
create or replace function find_student_location(p_registration_num in varchar2) return varchar2 is
    v_room_number camere.nr_camera%type;
    v_dorm_name camine.nume_camin%type;
begin
    select c.nume_camin, cm.nr_camera 
    into v_dorm_name, v_room_number
    from studenti s
    join cazari cz on s.id_student = cz.id_student
    join camere cm on cz.id_camera = cm.id_camera
    join camine c on cm.id_camin = c.id_camin
    where s.nr_matricol = lower(p_registration_num) and cz.status_cazare = 'activ';
    
    return 'Dormitory ' || v_dorm_name || ', Room ' || v_room_number;
exception
    when no_data_found then
        return 'The student was not found or does not have an active accommodation.';
    when too_many_rows then
        return 'Error: duplicate records found in the system for this student.';
end find_student_location;
/

-- ==============================================================================
-- 7. DECLANSATORI (TRIGGERS)
-- ==============================================================================
create or replace trigger trg_securitate_salariu
before update of salariu_baza on staff
for each row
begin
    if :new.salariu_baza < :old.salariu_baza then
        raise_application_error(-20001, 'Eroare: Este ilegala scaderea salariului!');
    end if;
end;
/

create or replace trigger trg_verificare_salariu
before insert or update of salariu_baza on staff
for each row
declare
    e_salariu_mic exception; 
    v_limita constant number := 3000;
begin
    if :new.salariu_baza < v_limita then
        raise e_salariu_mic; 
    end if;
exception
    when e_salariu_mic then
        raise_application_error(-20005, 'Eroare: Salariul introdus (' || :new.salariu_baza || ' RON) este sub pragul minim legal de ' || v_limita || ' RON.');
    when others then
        raise_application_error(-20000, 'Eroare sistem: ' || sqlerrm);
end;
/

create or replace trigger trg_comp_capacitate_camera
for insert or update on cazari
compound trigger

    type t_camere_modificate is table of number index by pls_integer;
    v_camere t_camere_modificate;
    v_capacitate camere.capacitate%type;
    v_ocupanti number;

    before statement is
    begin
        v_camere.delete;
    end before statement;

    after each row is
    begin
        if inserting or (updating and :new.status_cazare = 'activ') then
            v_camere(:new.id_camera) := 1;
        end if;
    end after each row;

    after statement is
        v_id_camera pls_integer;
    begin
        v_id_camera := v_camere.first;
        while v_id_camera is not null loop
            select capacitate into v_capacitate 
            from camere 
            where id_camera = v_id_camera;
            
            select count(*) into v_ocupanti 
            from cazari 
            where id_camera = v_id_camera and status_cazare = 'activ';
            
            if v_ocupanti > v_capacitate then
                raise_application_error(-20500, 'Eroare: Capacitatea maximă de ' || v_capacitate || ' locuri pentru camera ' || v_id_camera || ' a fost depăsită!');
            end if;
            
            v_id_camera := v_camere.next(v_id_camera);
        end loop;
    end after statement;
end trg_comp_capacitate_camera;
/

create or replace trigger trg_previne_stergere_student
before delete on studenti
for each row
declare
    v_cazari_active number;
begin
    select count(*) into v_cazari_active
    from cazari
    where id_student = :old.id_student and status_cazare = 'activ';

    if v_cazari_active > 0 then
        raise_application_error(-20501, 'Actiune blocată: Studentul ' || :old.nume || ' nu poate fi sters din sistem deoarece figurează cu o cazare activă.');
    end if;
end;
/

-- ==============================================================================
-- 8. TESTARE (BLOCURI ANONIME)
-- ==============================================================================

-- a. Test: operatii avizier (insert/commit/delete/rollback)
begin
    insert into avizier values (1, 'Curatenie generala Marti');
    commit;
    delete from avizier;
    rollback;
end;
/

-- b. Testare Pachet pkg_dorm_finance
-- testing package 1
exec pkg_dorm_finance.generate_monthly_invoices(11, 2025);
exec pkg_dorm_finance.apply_penalties(10, 11, 2025);

select * from (
    select f.id_factura, s.nume || ' ' || s.prenume as accommodated_student, f.luna, f.suma_plata, f.status_factura
    from facturi_cazare f
    join cazari cz on f.id_cazare = cz.id_cazare
    join studenti s on cz.id_student = s.id_student
    where f.luna = 11 and f.anul = 2025
    order by f.suma_plata desc
) where rownum <= 10;

declare
    v_total_due number;
    v_student_name varchar2(100);
begin
    select initcap(nume) || ' ' || initcap(prenume) 
    into v_student_name
    from studenti
    where id_student = 1;

    v_total_due := pkg_dorm_finance.get_student_debt(1);
    
    if v_total_due >= 0 then
        dbms_output.put_line('The student ' || v_student_name || ' has a total debt of: ' || v_total_due || ' RON.');
    end if;
end;
/

declare
    v_list pkg_dorm_finance.t_student_table;
begin
    v_list := pkg_dorm_finance.get_top_debtors(5);
    
    for i in 1..v_list.count loop
        dbms_output.put_line('Rank ' || i || ': ' || v_list(i).full_name || ' with an outstanding debt of ' || v_list(i).total_debt || ' RON.');
    end loop;
end;
/

/* ==============================================================================
   exercise 2: pl/sql package (composite types, exceptions, functions, and administration procedures)
   requirement: create a pl/sql package named pkg_dorm_admin for managing
   dormitory accommodations. the package must contain composite data structures (a record) and four subprograms:
   - a function that calculates the number of available beds in a specific room (handling the implicit no_data_found exception).
   - a function that returns a record containing statistics (total capacity, occupied beds, available beds) for a specific dormitory.
   - a procedure that assigns a student to the first available room in a dormitory specified by code, updating the cazari table (or raising an exception if there are no spots).
   - a procedure that clears all accommodations from a given academic year, updating the status and end date.
============================================================================== */

-- c. Testare Pachet pkg_dorm_admin
-- testing package 2
declare
    v_dorm_stats pkg_dorm_admin.t_dorm_stats;
    v_available_beds number;
begin
    dbms_output.put_line('--- PACKAGE: DORM ADMINISTRATION ---');
    
    pkg_dorm_admin.assign_student(5, 'moxa');
    
    v_available_beds := pkg_dorm_admin.get_room_availability(1);
    dbms_output.put_line('Available spots left in room with ID 1: ' || v_available_beds);
    
    v_dorm_stats := pkg_dorm_admin.get_dorm_stats(1);
    dbms_output.put_line('Moxa Statistics -> Total spots: ' || v_dorm_stats.total_capacity || 
                         ' | Occupied: ' || v_dorm_stats.occupied_beds || 
                         ' | Available: ' || v_dorm_stats.available_beds);

    pkg_dorm_admin.clear_accommodations('2023-2024');
end;
/

/* ==============================================================================
   exercise 3: independent stored function and multiple exception handling
   requirement: create an independent function that receives a student's registration 
   number (matricol) and returns their exact location (dormitory name and room number). 
   if the student does not exist or is not accommodated, catch the no_data_found exception. 
   if there is a database error and multiple active accommodations appear for the same student,
   catch too_many_rows. call the function via an anonymous block.
============================================================================== */

-- d. Testare Functie Independenta: find_student_location
-- testing independent function
declare
    v_result varchar2(200);
    v_valid_reg_num varchar2(20);
begin
    select s.nr_matricol into v_valid_reg_num
    from studenti s
    join cazari cz on s.id_student = cz.id_student
    where cz.status_cazare = 'activ'
    and rownum = 1;

    dbms_output.put_line('--- TESTING INDEPENDENT FUNCTION ---');
    
    v_result := find_student_location(v_valid_reg_num);
    dbms_output.put_line('Search by valid registration number "' || v_valid_reg_num || '": ' || v_result);
    
    v_result := find_student_location('fake_reg_num');
    dbms_output.put_line('Search by incorrect registration number: ' || v_result);
end;
/

-- e. Testare Trigger trg_verificare_salariu (salariu 2400 RON sub limita)
begin
    dbms_output.put_line('Incercare actualizare salariu la 2800 RON pentru angajatul cu ID-ul 1...');
    update staff 
    set salariu_baza = 2800 
    where id_staff = 1;
exception
    when others then
        dbms_output.put_line(sqlerrm);
end;
/
-- f. Testare Trigger trg_comp_capacitate_camera
declare
    v_id_student studenti.id_student%type := 2; 
    v_id_camera camere.id_camera%type := 1; 
begin
    dbms_output.put_line('--- TEST: trg_comp_capacitate_camera ---');
    dbms_output.put_line('Incercare inserare student ' || v_id_student || ' in camera ' || v_id_camera || '...');
    
    insert into cazari (id_student, id_camera, an_universitar, data_start, status_cazare)
    values (v_id_student, v_id_camera, '2024-2025', sysdate, 'activ');
    
    dbms_output.put_line('Operatiune reusită: Camera avea locuri libere.');
    rollback;

exception
    when others then
        if sqlcode = -20500 then
            dbms_output.put_line('SUCCES TEST. Mesaj captat:');
            dbms_output.put_line(sqlerrm);
        else
            dbms_output.put_line('A apărut altă eroare de sistem: ' || sqlerrm);
        end if;
        rollback;
end;
/
-- g. Testare Trigger trg_previne_stergere_student
declare
    v_id_student studenti.id_student%type := 1; 
begin
    dbms_output.put_line('--- TEST: trg_previne_stergere_student ---');
    dbms_output.put_line('Incercare stergere student cu ID-ul ' || v_id_student || ' din sistem...');
    
    delete from studenti 
    where id_student = v_id_student;
    
    dbms_output.put_line('Operatiune reusită: Studentul a fost sters deoarece nu avea cazări active.');
    rollback;

exception
    when others then
        if sqlcode = -20501 then
            dbms_output.put_line('SUCCES TEST. Mesaj captat:');
            dbms_output.put_line(sqlerrm);
        else
            dbms_output.put_line('A apărut altă eroare de sistem: ' || sqlerrm);
        end if;
        rollback;
end;
/
-- h. Blocuri Anonime PL/SQL (cursor, colectii, exceptii)
-- initial environment settings

-- exercise 1: Substitution variables, %type and alternative structures
declare
   v_matricol studenti.nr_matricol%type := 'fab_101';
   v_nume studenti.nume%type;
   v_an studenti.an_curent%type;
begin
   select nume, an_curent into v_nume, v_an 
   from studenti 
   where nr_matricol = v_matricol;
    if
v_an = '1' then
       dbms_output.put_line('Studentul ' || v_nume || ' este boboc (anul 1).');
   elsif v_an = '2' or v_an = '3' then
       dbms_output.put_line('Studentul ' || v_nume || ' este in ciclul de
licentă (anul ' || v_an || ').');
   else
       dbms_output.put_line('Studentul ' || v_nume || ' este la master (anul '
|| v_an || ').');
    end if;
end;
/

-- exercise 2: Implicit cursor, %rowtype and predefined exceptions
declare
    v_student studenti%rowtype;
begin
    select * into v_student 
    from studenti 
    where lower(nume) =
lower('Popescu');
    dbms_output.put_line('Student găsit: ' ||
v_student.nume || ' ' || v_student.prenume || ' - CNP: ' || v_student.cnp);
exception
    when no_data_found then
        dbms_output.put_line('Eroare: Nu s-a
găsit niciun student cu acest nume!');
    when too_many_rows then
       dbms_output.put_line('Eroare: Există mai multi studenti cu acest nume!
utilizati un criteriu de filtrare mai strict.');
end;
/

-- exercise 3: Explicit cursor, loop structure and %notfound attribute
declare
    cursor c_tarife is 
        select c.nume_camin, l.pret_buget 
        from camine c
        join lista_preturi_camin l on
c.id_camin = l.id_camin;
    v_nume camine.nume_camin%type;
    v_pret lista_preturi_camin.pret_buget%type;
begin
    dbms_output.put_line('--- lista tarife
buget ---');
    open c_tarife;
    loop
        fetch c_tarife into v_nume, v_pret;
        exit when c_tarife%notfound;
        dbms_output.put_line('Căminul ' ||
v_nume || ' are un tarif de: ' || v_pret || ' ron');
    end loop;
    close c_tarife;
end;
/

-- exercise 4: DML interaction and implicit cursor attributes (%rowcount, %notfound)
declare
    v_etaj camere.etaj%type :=
1;
    v_cod_camin camine.cod_camin%type :=
lower('moxa');
    v_capacitate camere.capacitate%type :=
3; 
begin
    if
v_capacitate < 2 then
       raise_application_error(-20002, 'Eroare: Capacitatea unei camere nu
poate fi mai mică decat 2!');
   else
       update camere 
       set capacitate = v_capacitate
       where etaj = v_etaj 
         and id_camin = (select id_camin from camine where cod_camin =
v_cod_camin);
       if sql%notfound then
           dbms_output.put_line('Nu s-au găsit camere la etajul ' || v_etaj || ' in
căminul specificat.');
       else
           dbms_output.put_line('S-a modificat capacitatea pentru ' || sql%rowcount
|| ' camere.');
       end if;
   end
if;
end;
/

-- exercise 5: Collection data types - index by pls_integer
declare
    type ang_table is table of staff%rowtype
index by pls_integer;
    v_tab ang_table;
    v_index pls_integer := 1;
begin
    for r_angajat in (select * from staff where
rownum <= 5) loop
        v_tab(v_index) := r_angajat;
        v_index := v_index + 1;
    end loop;
    dbms_output.put_line('--- Date extrase din
tabloul indexat ---');
    for i in v_tab.first .. v_tab.last loop
        dbms_output.put_line('Angajat: ' || v_tab(i).nume
|| ' ' || v_tab(i).prenume || ' - Salariu: ' || v_tab(i).salariu_baza);
    end loop;
    dbms_output.put_line('Total inregistrări in
tablou: ' || v_tab.count);
end;
/

-- exercise 6: Implicit cursor within a FOR loop structure
declare
   cursor c_facturi_mari is
       select f.id_factura, f.suma_plata, s.nume
       from facturi_cazare f
       join cazari z on f.id_cazare = z.id_cazare
       join studenti s on z.id_student = s.id_student
       where f.status_factura = 'neplatit' and f.suma_plata > 300;
begin
   dbms_output.put_line('--- Facturi restante > 300 ron ---');
    for
r_factura in c_facturi_mari loop
       dbms_output.put_line('Factura id: ' || r_factura.id_factura || ' | Sumă:
' || r_factura.suma_plata || ' ron | Student: ' || r_factura.nume);
    end
loop;
end;
/

-- exercise 7: Handling non-predefined Oracle exceptions (pragma exception_init)
declare
   del_exception exception;
   pragma exception_init(del_exception, -2292);
begin
   delete from camine;
exception
   when del_exception then
       dbms_output.put_line('Eroare: Nu puteti sterge căminul!');
       dbms_output.put_line('Există camere/date asignate acestuia (restrictie
referentială).');
       dbms_output.put_line('Cod eroare: ' || sqlcode);
       dbms_output.put_line('Mesaj eroare: ' || sqlerrm);
end;
/

-- exercise 8: User-defined exceptions (raise_application_error)
declare
   v_id_angajat staff.id_staff%type := 1;
    v_salariu_nou
staff.salariu_baza%type := 2400;
begin
    if
v_salariu_nou < 2500 then
       raise_application_error(-20001, 'Operatiune respinsă: Salariul introdus
(' || v_salariu_nou || ' ron) este sub pragul minim legal de 2500 ron!');
    else
       update staff 
       set salariu_baza = v_salariu_nou 
       where id_staff = v_id_angajat;
       dbms_output.put_line('Salariul a fost actualizat cu succes la ' ||
v_salariu_nou || ' ron.');
    end
if;
end;
/

-- exercise 9: Parameterized explicit cursor and while loop
declare
   v_cod_camin camine.cod_camin%type := lower('moxa'); 
   cursor c_studenti_camin(p_cod varchar2) is
       select s.nume, s.prenume, c.nr_camera, k.nume_camin
       from studenti s
       join cazari z on s.id_student = z.id_student
       join camere c on z.id_camera = c.id_camera
       join camine k on c.id_camin = k.id_camin
       where k.cod_camin = p_cod and z.status_cazare = 'activ'
       order by c.nr_camera;
   v_nume studenti.nume%type;
   v_prenume studenti.prenume%type;
   v_camera camere.nr_camera%type;
    v_nume_camin
camine.nume_camin%type;
    v_contor
number := 0;
begin
   open c_studenti_camin(v_cod_camin);
   fetch c_studenti_camin into v_nume, v_prenume, v_camera, v_nume_camin;
   dbms_output.put_line('--- Primii 5 studenti cazati in căminul ' ||
v_nume_camin || ' ---');
   while c_studenti_camin%found and v_contor < 5 loop
       v_contor := v_contor + 1;
       dbms_output.put_line(v_contor || '. ' || v_nume || ' ' || v_prenume || '
(Camera: ' || v_camera || ')');
       fetch c_studenti_camin into v_nume, v_prenume, v_camera, v_nume_camin;
    end
loop;
    if
v_contor = 0 then
       dbms_output.put_line('Nu s-au găsit studenti activi cazati in acest
cămin.');
    end
if;
   close c_studenti_camin;
end;
/

-- exercise 10: Case expression, DML and dup_val_on_index exception
declare
    v_cod_camin camine.cod_camin%type :=
lower('occid'); 
    v_nume_camin camine.nume_camin%type :=
lower('Occidentului');
    v_adresa camine.adresa%type :=
lower('Occidentului 7');
    v_mixt_text
varchar2(2) := lower('da');
   v_if_mixt camine.if_mixt%type;
begin
   v_if_mixt := case v_mixt_text 
                    when 'da' then 1 
                    when 'nu' then 0 
                    else 0 
                 end;
   insert into camine (cod_camin, nume_camin, adresa, if_mixt)
   values (v_cod_camin, v_nume_camin, v_adresa, v_if_mixt);
   dbms_output.put_line('Succes: A fost inserat ' || sql%rowcount || '
cămin nou (' || v_nume_camin || ').');
exception
   when dup_val_on_index then
       dbms_output.put_line('Eroare: Codul de cămin "' || v_cod_camin ||
'" există deja in baza de date!');
       dbms_output.put_line('A fost incălcată constrangerea unique
(uq_cod_camin).');
   when others then
       dbms_output.put_line('A apărut o eroare neasteptată: ' || sqlerrm);
end;
/

-- i. Blocuri Anonime Exceptii
-- Exercise 1
-- Requirement: Display the name and faculty of the student occupying a specific accommodation spot (entered by ID). If the accommodation ID does not exist, catch the implicit no_data_found exception. If the student is in their final year (year 3 or master 2), display a special warning.
declare
    v_id_cazare cazari.id_cazare%type := 1;
    v_nume studenti.nume%type;
    v_an studenti.an_curent%type;
    v_facultate studenti.facultate%type;
begin
    select s.nume, s.an_curent, s.facultate
    into v_nume, v_an, v_facultate
    from studenti s
    join cazari z on s.id_student = z.id_student
    where z.id_cazare = v_id_cazare;

    dbms_output.put_line('Student: ' || initcap(v_nume) || ' | Facultate: ' || initcap(v_facultate));

    if (v_an = '3' or v_an = 'm2') then
        dbms_output.put_line('Atentie: Studentul este in an terminal.');
    end if;

exception
    when no_data_found then
        dbms_output.put_line('Eroare: Nu există nicio inregistrare de cazare cu id-ul ' || v_id_cazare || '.');
    when others then
        dbms_output.put_line('Eroare sistem: ' || sqlerrm);
end;
/

-- Exercise 3
-- Requirement: Identify the student living in a specific room of a dormitory. If multiple students live in that room (capacity > 1), the SELECT...INTO statement will trigger the implicit too_many_rows exception.
declare
    v_nume_student studenti.nume%type;
    v_camera camere.nr_camera%type := '101';
    v_cod camine.cod_camin%type := lower('moxa');
begin
    select s.nume into v_nume_student
    from studenti s
    join cazari z on s.id_student = z.id_student
    join camere c on z.id_camera = c.id_camera
    join camine k on c.id_camin = k.id_camin
    where c.nr_camera = v_camera and k.cod_camin = v_cod and z.status_cazare = 'activ';

    dbms_output.put_line('In camera ' || v_camera || ' locuieste: ' || initcap(v_nume_student));

exception
    when too_many_rows then
        dbms_output.put_line('Eroare: In camera ' || v_camera || ' sunt cazati mai multi studenti. Folositi un cursor pentru listare.');
    when no_data_found then
        dbms_output.put_line('Eroare: Camera este momentan liberă.');
    when others then
        dbms_output.put_line('Eroare sistem: ' || sqlerrm);
end;
/

-- Exercise 4
-- Requirement: Attempt to update the tuition fee rate for a dormitory. If the new rate is greater than 1000 RON, stop the execution using raise_application_error (explicit exception with a custom error code).
declare
    v_id_camin camine.id_camin%type := 1;
    v_pret_nou number := 1200;
begin
    if v_pret_nou > 1000 then
        raise_application_error(-20101, 'Eroare: Tariful de ' || v_pret_nou || ' depăseste plafonul maxim admis de universitate.');
    else
        update lista_preturi_camin
        set pret_taxa = v_pret_nou
        where id_camin = v_id_camin;
        
        if sql%notfound then
            dbms_output.put_line('Eroare: Nu s-a găsit nicio inregistrare de pret pentru id-ul ' || v_id_camin || '.');
        else
            dbms_output.put_line('Succes: Tariful a fost actualizat.');
        end if;
    end if;
    
    rollback;
exception
    when others then
        dbms_output.put_line('Eroare sistem: ' || sqlerrm);
end;
/

-- Exercise 5
-- Requirement: List the unpaid invoices of a student. If the total amount of arrears exceeds 1500 RON, trigger an explicit exception e_student_restant.
declare
    cursor c_facturi(p_id number) is
        select suma_plata from facturi_cazare f
        join cazari z on f.id_cazare = z.id_cazare
        where z.id_student = p_id and f.status_factura = 'neplatit';
    
    v_suma_totala number := 0;
    v_suma_factura number;
    v_id_stud number := 1;
    e_student_restant exception; 
begin
    open c_facturi(v_id_stud);
    fetch c_facturi into v_suma_factura;
    
    while c_facturi%found loop
        v_suma_totala := v_suma_totala + v_suma_factura;
        fetch c_facturi into v_suma_factura;
    end loop;
    close c_facturi;

    dbms_output.put_line('Total restante student: ' || v_suma_totala || ' RON.');

    if v_suma_totala > 1500 then
        raise e_student_restant;
    end if;

exception
    when e_student_restant then
        dbms_output.put_line('Atentie: Studentul are restante critice! Se recomandă blocarea accesului la servicii.');
    when others then
        dbms_output.put_line('Eroare sistem: ' || sqlerrm);
end;
/

